# Generated by Django 2.2.1 on 2019-06-03 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upost', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='interest',
            name='image',
            field=models.ImageField(null=True, upload_to='interests'),
        ),
    ]
