# Generated by Django 2.2.1 on 2019-05-29 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upost', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='interests',
            field=models.ManyToManyField(blank=True, null=True, to='upost.Interest'),
        ),
    ]
