# Generated by Django 2.2.1 on 2019-05-30 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upost', '0002_auto_20190529_1210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='interests',
            field=models.ManyToManyField(blank=True, to='upost.Interest'),
        ),
    ]
