# Generated by Django 2.2.1 on 2019-06-04 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upost', '0002_interest_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='cost',
            field=models.IntegerField(blank=True, db_column='Cost', default=0, null=True),
        ),
    ]
