# Generated by Django 2.2.1 on 2019-06-04 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upost', '0003_auto_20190604_1118'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postevent',
            name='planned_end_time',
        ),
        migrations.RemoveField(
            model_name='postevent',
            name='planned_start_time',
        ),
        migrations.AlterField(
            model_name='postevent',
            name='planned_end_date',
            field=models.DateTimeField(db_column='Planned_end_datetime'),
        ),
        migrations.AlterField(
            model_name='postevent',
            name='planned_start_date',
            field=models.DateTimeField(db_column='Planned_start_datetime'),
        ),
    ]
