# Generated by Django 2.2.1 on 2019-05-30 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upost', '0003_auto_20190529_2339'),
    ]

    operations = [
        migrations.AddField(
            model_name='interest',
            name='descripton',
            field=models.CharField(default='description', max_length=50),
            preserve_default=False,
        ),
    ]
