# Generated by Django 2.2.1 on 2019-05-30 22:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('upost', '0005_auto_20190530_1611'),
    ]

    operations = [
        migrations.RenameField(
            model_name='interest',
            old_name='descripton',
            new_name='description',
        ),
    ]
