# Generated by Django 2.2.1 on 2019-05-31 22:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('upost', '0004_contentchannel_channel_description'),
        ('upost', '0006_auto_20190530_1616'),
    ]

    operations = [
    ]
